"use client";
import {useMemo,useState} from "react";
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Math.max(0,n||0));
const yrs=(y,m)=>Number(y||0)+Number(m||0)/12;
const ageOn=(dob,date)=>(new Date(date+"T00:00:00")-new Date(dob+"T00:00:00"))/(365.2425*86400000);
const between=(a,b)=>Math.max(0,(new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/(365.2425*86400000));
function addYears(date,y){const d=new Date(date+"T00:00:00");d.setFullYear(d.getFullYear()+y);return d.toISOString().slice(0,10)}
function fireRed(age,s){if(s>=30||age>=65||(age>=60&&s>=25))return 1;if(age>=60&&s>=5)return Math.min(1,.85+(age-60)*.03);if(age>=55&&s>=5){if(s>=29)return .95;if(s>=28)return .90;if(s>=27)return .85;if(s>=26)return .80;if(s>=25)return .75;if(s>=24)return .70;if(s>=23)return .65;return .60}return 0}
function genRed(age,s){if(s>=30||age>=65||(age>=60&&s>=25))return 1;if(age>=60&&s>=5)return Math.min(1,.85+(age-60)*.03);if(age>=50&&s>=20){if(s>=29)return .95;if(s>=28)return .90;if(s>=27)return .85;if(s>=26)return .80;if(s>=25)return .75;if(s>=24)return .70;if(s>=23)return .65;return .60}return 0}
function leoRed(age,s,l){if(s>=30||(age>=55&&l>=5))return 1;if((age>=50&&l>=15)||(s>=25&&l>=15)){if(age>=54)return .96;if(age>=53)return s>=29?.95:.92;if(age>=52)return s>=29?.95:s>=28?.90:.88;if(age>=51)return s>=29?.95:s>=28?.90:s>=27?.85:.84;if(age>=50)return s>=29?.95:s>=28?.90:s>=27?.85:.80}return 0}
const red=(t,a,s,l)=>t==="leo"?leoRed(a,s,l):t==="fire"?fireRed(a,s):genRed(a,s);
const label=r=>r===1?"Unreduced retirement":r>0?"Reduced retirement":"Not yet eligible to begin benefit";
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export default function Home(){
 const today=new Date().toISOString().slice(0,10);
 const [type,setType]=useState("fire"),[dob,setDob]=useState("1987-12-01"),[sy,setSy]=useState("18"),[sm,setSm]=useState("0"),[leoY,setLeoY]=useState("18"),[afc,setAfc]=useState("85000"),[salary,setSalary]=useState("90000"),[raise,setRaise]=useState("3"),[sick,setSick]=useState("0"),[retire,setRetire]=useState(addYears(today,12));
 const c=useMemo(()=>{const cs=yrs(sy,sm),future=between(today,retire),age=ageOn(dob,retire),ls=type==="leo"?Number(leoY||0)+future:0,g=Number(raise||0)/100,pa=Math.max(Number(afc||0),Number(salary||0)*Math.pow(1+g,Math.max(0,future-2))),sd=Number(sick||0),sickMonths=Math.floor(sd/20)+(sd%20>0?1:0),service=cs+future+sickMonths/12,r=red(type,age,service,ls),annual=pa*.0185*service*r;return{cs,future,age,ls,pa,sickMonths,service,r,annual,monthly:annual/12,earned:Number(afc||0)*.0185*cs/12}},[type,dob,sy,sm,leoY,afc,salary,raise,sick,retire,today]);
 const miles=[0,5,10,15,20].map(n=>{const d=addYears(today,n),a=ageOn(dob,d),s=c.cs+n,l=type==="leo"?Number(leoY||0)+n:0,pa=Math.max(Number(afc||0),Number(salary||0)*Math.pow(1+Number(raise||0)/100,Math.max(0,n-2))),r=red(type,a,s,l);return{n,a,s,r,m:pa*.0185*s*r/12}});
 return <main>
 <header><div className="brand"><span className="mark">NC</span><b>RETIREMENT COMPASS</b></div><nav><a href="#calculator">Calculator</a><a href="#timeline">Timeline</a><a href="#how">How it works</a></nav></header>
 <section className="hero"><div><div className="eyebrow">NORTH CAROLINA LGERS RETIREMENT PLANNER</div><h1>Know what your pension is <em>really</em> worth.</h1><p>Built for North Carolina firefighters, law enforcement officers, and local government employees. See what you have earned, what happens if you leave, and what staying longer could mean.</p><a className="primary" href="#calculator">Calculate my retirement →</a></div><div className="heroCard"><small>THE QUESTION WE ANSWER</small><strong>“When can I retire—and how much will I actually get?”</strong><div className="formula">AFC × 1.85% × Service</div><span>LGERS Maximum Allowance formula</span></div></section>
 <section id="calculator" className="calc"><div className="formPanel"><div className="sectionLabel">01 / YOUR LGERS RECORD</div><h2>Tell us where you are today.</h2>
 <Field label="I am a"><select value={type} onChange={e=>setType(e.target.value)}><option value="fire">Firefighter / Rescue Worker</option><option value="leo">Law Enforcement Officer</option><option value="general">Other Local Government Employee</option></select></Field>
 <div className="grid2"><Field label="Date of birth"><input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></Field><Field label="Current AFC" hint="Highest 48 consecutive months"><input value={afc} onChange={e=>setAfc(e.target.value.replace(/[^0-9.]/g,""))}/></Field></div>
 <div className="grid2"><Field label="LGERS service — years"><input type="number" min="0" value={sy} onChange={e=>setSy(e.target.value)}/></Field><Field label="Additional months"><input type="number" min="0" max="11" value={sm} onChange={e=>setSm(e.target.value)}/></Field></div>
 {type==="leo"&&<Field label="Years served as a sworn LEO"><input type="number" min="0" value={leoY} onChange={e=>setLeoY(e.target.value)}/></Field>}
 <div className="sectionLabel gap">02 / YOUR FUTURE</div><div className="grid2"><Field label="Current annual salary"><input value={salary} onChange={e=>setSalary(e.target.value.replace(/[^0-9.]/g,""))}/></Field><Field label="Expected annual raise"><div className="suffix"><input type="number" step=".1" value={raise} onChange={e=>setRaise(e.target.value)}/><i>%</i></div></Field></div>
 <div className="grid2"><Field label="Unused sick leave (days)" hint="Optional; applied at retirement"><input type="number" min="0" value={sick} onChange={e=>setSick(e.target.value)}/></Field><Field label="Retirement date"><input type="date" min={today} value={retire} onChange={e=>setRetire(e.target.value)}/></Field></div></div>
 <aside className="results"><div className="resultTop"><small>PROJECTED MONTHLY PENSION</small><strong>{money(c.monthly)}<i>/mo</i></strong><span className={c.r===1?"good":c.r>0?"warn":"muted"}>{label(c.r)}</span></div>
 <div className="stats"><div><span>Annual pension</span><b>{money(c.annual)}</b></div><div><span>Retirement age</span><b>{c.age.toFixed(1)}</b></div><div><span>Creditable service</span><b>{c.service.toFixed(1)} yrs</b></div><div><span>Projected AFC</span><b>{money(c.pa)}</b></div>{c.r>0&&c.r<1&&<div><span>Benefit factor</span><b>{Math.round(c.r*100)}%</b></div>}{c.sickMonths>0&&<div><span>Sick leave credit</span><b>+{c.sickMonths} mo</b></div>}</div>
 <div className="earned"><span>FORMULA VALUE OF SERVICE EARNED TO DATE</span><strong>{money(c.earned)}<i>/mo</i></strong><p>Based on current AFC and service. Eligibility and reductions determine when and how much can actually be paid.</p></div></aside></section>
 <section id="timeline" className="timeline"><div className="sectionLabel">03 / LOOK AHEAD</div><h2>What happens if you stay?</h2><p className="lead">Same assumptions. Different dates. See the tradeoff.</p><div className="cards">{miles.map(x=><div className="mile" key={x.n}><small>{x.n===0?"TODAY":"+"+x.n+" YEARS"}</small><b>{x.r?money(x.m):"Not eligible"}</b><span>{x.s.toFixed(1)} yrs service</span><span>Age {x.a.toFixed(1)}</span><em>{x.r===1?"UNREDUCED":x.r>0?"REDUCED":"DEFERRED"}</em></div>)}</div></section>
 <section id="how" className="how"><div><div className="sectionLabel">HOW IT WORKS</div><h2>Built around the LGERS formula—not your account balance.</h2></div><div className="howGrid"><article><b>1.85%</b><span>Benefit multiplier</span></article><article><b>AFC</b><span>Highest 48 consecutive months</span></article><article><b>Service</b><span>Creditable LGERS service</span></article></div></section>
 <section className="notice"><b>Planning estimate, not an official benefit calculation.</b><p>NC Retirement Compass is an independent educational tool and is not affiliated with the North Carolina Retirement Systems. Actual benefits are determined by the Retirement Systems Division under applicable law. Confirm retirement decisions with your official ORBIT estimate.</p><div><a href="https://www.myncretirement.com/" target="_blank" rel="noreferrer">NC Retirement Systems ↗</a><a href="https://orbit.myncretirement.com/" target="_blank" rel="noreferrer">ORBIT ↗</a></div></section>
 <footer><b>NC RETIREMENT COMPASS</b><span>Clearer retirement planning for North Carolina public servants.</span></footer></main>
}