"use client";
import {useMemo,useState} from "react";
import {NetEstimate,TaxSettings} from "./net-estimate";
import {DEFAULT_TAX} from "./pension-net.mjs";
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Math.max(0,n||0));
const yrs=(y,m)=>Number(y||0)+Number(m||0)/12;
const ym=v=>{const total=Math.max(0,Math.round(Number(v||0)*12)),y=Math.floor(total/12),m=total%12;return (y?y+" year"+(y===1?"":"s"):"")+(y&&m?", ":"")+(m?m+" month"+(m===1?"":"s"):y?"":"0 months")};
const ageYM=v=>ym(v);
const untilYM=(a,b)=>ym(between(a,b));
const ageOn=(dob,date)=>between(dob,date);
const between=(a,b)=>{
 if(!a||!b||b<a)return 0;
 const start=new Date(a+"T00:00:00Z"),end=new Date(b+"T00:00:00Z");
 if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime()))return 0;
 let months=(end.getUTCFullYear()-start.getUTCFullYear())*12+end.getUTCMonth()-start.getUTCMonth();
 let anchor=addMonths(a,months);if(anchor>b)anchor=addMonths(a,--months);
 const next=addMonths(a,months+1),fraction=(end-new Date(anchor+"T00:00:00Z"))/(new Date(next+"T00:00:00Z")-new Date(anchor+"T00:00:00Z"));
 return Math.max(0,(months+fraction)/12);
};
function addYears(date,y){const d=new Date(date+"T00:00:00Z");d.setUTCFullYear(d.getUTCFullYear()+y);return d.toISOString().slice(0,10)}
function addMonths(date,m){const d=new Date(date+"T00:00:00Z"),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+m);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10)}
// Approximate the highest 48-month average by replacing historical months with future salary.
// The entered AFC remains authoritative at zero future service.
function projectAfc(current,salary,raise,future){
 const afc=Math.max(0,Number(current||0)),pay=Math.max(0,Number(salary||0)),months=Math.max(0,future*12),g=Number(raise||0)/100;
 if(!months||!pay)return afc;
 const start=Math.max(0,months-48);let total=afc*Math.max(0,48-months);
 for(let t=start;t<months;){const end=Math.min(months,Math.floor(t+1e-8)+1);total+=pay*Math.pow(1+g,t/12)*(end-t);t=end}
 return Math.max(afc,total/48);
}
const niceDate=d=>d?new Date(d+"T00:00:00").toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}):"—";
function dateAtAge(dob,targetAge,today){if(!dob)return today;const b=new Date(dob+"T00:00:00Z");if(Number.isNaN(b.getTime()))return today;const d=new Date(Date.UTC(b.getUTCFullYear()+targetAge,b.getUTCMonth(),b.getUTCDate()));const iso=d.toISOString().slice(0,10);return iso<today?today:iso}
function sickCreditFromHours(hours,monthlyAccrual){if(!(hours>0)||!(monthlyAccrual>0))return{days:0,months:0,years:0};const days=hours/monthlyAccrual,months=Math.ceil(days/20);return{days,months,years:months/12}}
function fireRed(age,s){if(s>=30||(age>=65&&s>=5)||(age>=60&&s>=25))return 1;if(age>=60&&s>=5)return Math.min(1,.85+(age-60)*.03);if(age>=55&&s>=5){if(s>=29)return .95;if(s>=28)return .90;if(s>=27)return .85;if(s>=26)return .80;if(s>=25)return .75;if(s>=24)return .70;if(s>=23)return .65;return .60}return 0}
function genRed(age,s){if(s>=30||(age>=65&&s>=5)||(age>=60&&s>=25))return 1;if(age>=60&&s>=5)return Math.min(1,.85+(age-60)*.03);if(age>=50&&s>=20){if(s>=29)return .95;if(s>=28)return .90;if(s>=27)return .85;if(s>=26)return .80;if(s>=25)return .75;if(s>=24)return .70;if(s>=23)return .65;return .60}return 0}
function leoRed(age,s,l){if(s>=30||(age>=55&&l>=5))return 1;if((age>=50&&l>=15)||(s>=25&&l>=15)){if(age>=54)return .96;if(age>=53)return s>=29?.95:.92;if(age>=52)return s>=29?.95:s>=28?.90:.88;if(age>=51)return s>=29?.95:s>=28?.90:s>=27?.85:.84;if(age>=50)return s>=29?.95:s>=28?.90:s>=27?.85:.80}return 0}
const red=(t,a,s,l)=>t==="leo"?leoRed(a,s,l):t==="fire"?fireRed(a,s):genRed(a,s);
const label=r=>r===1?"Unreduced retirement":r>0?"Reduced retirement":"Not yet eligible to begin benefit";
function Info({text}){return <span className="info" tabIndex="0">?<span className="tip">{text}</span></span>}
function Field({label,children,hint,info,prefix,suffix}){return <label className={"field"+(prefix?" hasPrefix":"")+(suffix?" hasSuffix":"")}><span className="floatLabel">{label} {info&&<Info text={info}/>}</span>{prefix&&<span className="fieldPrefix">{prefix}</span>}{children}{suffix&&<span className="fieldSuffix">{suffix}</span>}{hint&&<small>{hint}</small>}</label>}
const commas=v=>v===""?"":Number(String(v).replace(/,/g,"")||0).toLocaleString("en-US");
const raw=e=>e.target.value.replace(/[^0-9.]/g,"").replace(/^0+(?=\d)/,"");
export default function Home(){
 const today=new Date().toISOString().slice(0,10);
 const [tax,setTax]=useState({...DEFAULT_TAX});
 const [mode,setMode]=useState("basic"),[type,setType]=useState("fire"),[dob,setDob]=useState(""),[sy,setSy]=useState("0"),[sm,setSm]=useState("0"),[leoY,setLeoY]=useState("0"),[afc,setAfc]=useState("0"),[salary,setSalary]=useState("0"),[raise,setRaise]=useState("0"),[sick,setSick]=useState("0"),[sickMonthly,setSickMonthly]=useState("0"),[sickUsePct,setSickUsePct]=useState("0"),[projectSick,setProjectSick]=useState(false),[vacToSick,setVacToSick]=useState(false),[vacEarnAnnual,setVacEarnAnnual]=useState("0"),[vacUsePct,setVacUsePct]=useState("0"),[vacConvertPct,setVacConvertPct]=useState("0"),[useSick,setUseSick]=useState(false),[beneficiaryDob,setBeneficiaryDob]=useState(""),[retire,setRetire]=useState("");
 const basic=useMemo(()=>{const cs=yrs(sy,sm);if(!dob||cs<=0||Number(afc||0)<=0)return null;for(let m=0;m<=600;m++){const d=addMonths(today,m),future=between(today,d),age=ageOn(dob,d),service=cs+future,leoService=type==="leo"?Number(leoY||0)+future:0;if(red(type,age,service,leoService)===1)return{date:d,age,service,months:m,monthly:Number(afc||0)*.0185*service/12,annual:Number(afc||0)*.0185*service,reason:service>=30?"30 years of creditable service":type==="leo"&&age>=55&&leoService>=5?"Age 55 with at least 5 years as an LEO":age>=65?"Age 65 with at least 5 years":"Age 60 with at least 25 years"}}return null},[today,dob,sy,sm,afc,type,leoY]);
 const c=useMemo(()=>{const cs=yrs(sy,sm),target=retire||today,future=between(today,target),futureMonths=Math.max(0,Math.round(future*12)),age=ageOn(dob,target),ls=type==="leo"?Number(leoY||0)+future:0,g=Number(raise||0)/100,pa=projectAfc(afc,salary,raise,future),monthlyAccrual=Math.max(0,Number(sickMonthly||0)),sickRetain=Math.max(0,1-Number(sickUsePct||0)/100),vacRetain=Math.max(0,1-Number(vacUsePct||0)/100),futureSick=projectSick?futureMonths*monthlyAccrual*sickRetain:0,futureVac=projectSick&&vacToSick?future/1*Number(vacEarnAnnual||0)*vacRetain*(Number(vacConvertPct||0)/100):0,projectedSickHours=Math.max(0,Number(sick||0)+futureSick+futureVac),sc=sickCreditFromHours(projectedSickHours,monthlyAccrual),sickCredit=useSick?sc.years:0,service=cs+future+sickCredit,r=red(type,age,service,ls),annual=pa*.0185*service*r;return{cs,future,age,ls,pa,futureSick,futureVac,sickMonths:sc.months,sickCredit,service,r,annual,monthly:annual/12,earned:Number(afc||0)*.0185*cs/12,sickDays:sc.days,projectedSickHours,currentSick:sickCreditFromHours(Number(sick||0),monthlyAccrual)}} ,[type,dob,sy,sm,leoY,afc,salary,raise,sick,sickMonthly,sickUsePct,projectSick,vacToSick,vacEarnAnnual,vacUsePct,vacConvertPct,useSick,retire,today]);
 const earliestMax=useMemo(()=>{for(let m=0;m<=600;m++){const d=addMonths(today,m),future=between(today,d),age=ageOn(dob,d),leoService=type==="leo"?Number(leoY||0)+future:0,monthlyAccrual=Math.max(0,Number(sickMonthly||0)),sickRetain=Math.max(0,1-Number(sickUsePct||0)/100),vacRetain=Math.max(0,1-Number(vacUsePct||0)/100),projectedSickHours=Math.max(0,Number(sick||0)+(projectSick?m*monthlyAccrual*sickRetain:0)+(projectSick&&vacToSick?future*Number(vacEarnAnnual||0)*vacRetain*(Number(vacConvertPct||0)/100):0)),sc=sickCreditFromHours(projectedSickHours,monthlyAccrual),service=c.cs+future+(useSick?sc.years:0),r=red(type,age,service,leoService);if(r===1){const g=Number(raise||0)/100,projectedAfc=projectAfc(afc,salary,raise,future),monthly=projectedAfc*.0185*service/12,serviceNoLeave=c.cs+future,monthlyNoLeave=projectedAfc*.0185*serviceNoLeave/12,pensionAdded=monthly-monthlyNoLeave;return{date:d,age,service,serviceNoLeave,projectedAfc,monthly,monthlyNoLeave,pensionAdded,sickHours:projectedSickHours,sickMonths:sc.months,reason:service>=30?"30 years of creditable service":type==="leo"&&age>=55&&leoService>=5?"Age 55 with at least 5 years as an LEO":age>=65?"Age 65 with at least 5 years":"Age 60 with at least 25 years"}}}return null},[today,dob,type,leoY,c.cs,sick,sickMonthly,sickUsePct,projectSick,vacToSick,vacEarnAnnual,vacUsePct,vacConvertPct,useSick,raise,afc,salary]);
 const leaveProjection=useMemo(()=>{const target=retire||earliestMax?.date;if(!target)return{hours:Number(sick||0),futureSick:0,futureVac:0,days:0,months:0,date:null};const future=between(today,target),months=Math.max(0,Math.round(future*12)),monthlyAccrual=Math.max(0,Number(sickMonthly||0)),sickRetain=Math.max(0,1-Number(sickUsePct||0)/100),vacRetain=Math.max(0,1-Number(vacUsePct||0)/100),futureSick=projectSick?months*monthlyAccrual*sickRetain:0,futureVac=projectSick&&vacToSick?future*Number(vacEarnAnnual||0)*vacRetain*(Number(vacConvertPct||0)/100):0,hours=Math.max(0,Number(sick||0)+futureSick+futureVac),sc=sickCreditFromHours(hours,monthlyAccrual);return{hours,futureSick,futureVac,days:sc.days,months:sc.months,date:target}},[retire,earliestMax,today,sick,sickMonthly,sickUsePct,projectSick,vacToSick,vacEarnAnnual,vacUsePct,vacConvertPct]);
 const leaveNow=useMemo(()=>{
 const cs=c.cs,leo=Number(leoY||0),credit=useSick?c.currentSick.years:0,afcNow=Number(afc||0);
 // Service and AFC freeze at separation. Sick credit expires for starts beyond 365 days.
 const dates=new Set([today]);
 for(let m=1;m<=600;m++)dates.add(addMonths(today,m));
 for(let a=0;a<=110;a++)dates.add(dateAtAge(dob,a,today));
 let first=null,max=null;
 for(const date of [...dates].sort()){
  const days=(new Date(date+"T00:00:00Z")-new Date(today+"T00:00:00Z"))/86400000;
  const sickCredit=days<=365?credit:0,service=cs+sickCredit,age=ageOn(dob,date);
  const factor=dob&&(days<=365||cs>=5)?red(type,age,service,leo):0;
  const amount=afcNow*.0185*service*factor/12;
  if(!first&&factor>0)first={date,age,amount,service,sickCredit,factor};
  if(!max&&factor===1)max={date,age,amount,service,sickCredit,factor};
  if(first&&max)break;
 }
 const todayService=cs+credit,todayFactor=dob?red(type,ageOn(dob,today),todayService,leo):0;
 return{first,max,todayService,todayFactor,todayAmount:afcNow*.0185*todayService*todayFactor/12};
 },[c.cs,c.currentSick.years,useSick,dob,today,type,leoY,afc]);
 const earliestWithoutLeave=useMemo(()=>{for(let m=0;m<=600;m++){const d=addMonths(today,m),future=between(today,d),age=ageOn(dob,d),leoService=type==="leo"?Number(leoY||0)+future:0,service=c.cs+future;if(red(type,age,service,leoService)===1)return{date:d,months:m}}return null},[today,dob,type,leoY,c.cs]);
 const leaveAdvantage=earliestMax&&earliestWithoutLeave?Math.max(0,Math.round(between(earliestMax.date,earliestWithoutLeave.date)*12)):0;
 const miles=[0,5,10,15,20].map(n=>{const d=addYears(today,n),a=ageOn(dob,d),monthlyAccrual=Math.max(0,Number(sickMonthly||0)),sickRetain=Math.max(0,1-Number(sickUsePct||0)/100),vacRetain=Math.max(0,1-Number(vacUsePct||0)/100),projectedHours=Math.max(0,Number(sick||0)+(projectSick?n*12*monthlyAccrual*sickRetain:0)+(projectSick&&vacToSick?n*Number(vacEarnAnnual||0)*vacRetain*(Number(vacConvertPct||0)/100):0)),sc=sickCreditFromHours(projectedHours,monthlyAccrual),sv=c.cs+n+(useSick?sc.years:0),l=type==="leo"?Number(leoY||0)+n:0,pa=projectAfc(afc,salary,raise,n),r=red(type,a,sv,l);return{n,a,s:sv,r,m:pa*.0185*sv*r/12}});
 return <main>
 <header><div className="brand"><span className="mark">NC</span><b>RETIREMENT COMPASS</b></div><nav><a href="#calculator">Calculator</a><a href="#timeline">Timeline</a><a href="#how">How it works</a></nav></header>
 <section className="hero"><div><div className="eyebrow">NORTH CAROLINA LGERS RETIREMENT PLANNER</div><h1>Know what your pension is <em>really</em> worth.</h1><p>Built for North Carolina firefighters, law enforcement officers, and local government employees. See what you have earned, what happens if you leave, and what staying longer could mean.</p><a className="primary" href="#calculator">Calculate my retirement →</a></div><div className="heroCard"><small>THE QUESTION WE ANSWER</small><strong>“When can I retire—and how much will I actually get?”</strong><div className="formula">AFC × 1.85% × Service</div><span>LGERS Maximum Allowance formula</span></div></section>
 <section id="calculator" className="calculatorShell"><div className="modeSwitch"><button type="button" className={mode==="basic"?"active":""} onClick={()=>setMode("basic")}><b>Basic Calculator</b><span>Earliest full retirement + Maximum Allowance</span></button><button type="button" className={mode==="advanced"?"active":""} onClick={()=>setMode("advanced")}><b>Advanced Calculator</b><span>Salary growth, leave, survivor options + more</span></button></div>
<TaxSettings settings={tax} onChange={setTax}/>
{mode==="basic"?<div className="calc basicCalc"><div className="formPanel"><div className="sectionLabel">BASIC LGERS CALCULATOR</div><h2>When can I retire with my full pension?</h2><Field label="I am a"><select value={type} onChange={e=>setType(e.target.value)}><option value="fire">Firefighter / Rescue Worker</option><option value="leo">Law Enforcement Officer</option><option value="general">Other Local Government Employee</option></select></Field><div className="grid2"><Field label="Date of birth"><input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></Field><Field label="Current AFC" prefix="$" info="Average Final Compensation (AFC) is generally your highest 48 consecutive months of eligible LGERS compensation. Use the AFC shown in ORBIT if you have it."><input inputMode="decimal" value={commas(afc)} onChange={e=>setAfc(raw(e))}/></Field></div><div className="grid2"><Field label="Current LGERS service — years" info="Enter the full years of creditable LGERS service shown in ORBIT."><input type="number" min="0" value={sy} onChange={e=>setSy(e.target.value)}/></Field><Field label="Additional months" info="Months beyond the full years. Example: 18 years, 7 months."><input type="number" min="0" max="11" value={sm} onChange={e=>setSm(e.target.value)}/></Field></div>{type==="leo"&&<Field label="Years served as a sworn LEO"><input type="number" min="0" value={leoY} onChange={e=>setLeoY(e.target.value)}/></Field>}<button type="button" className="advancedLink" onClick={()=>setMode("advanced")}>Want to include sick leave, vacation and salary growth? Open Advanced →</button></div><aside className="results basicResult">{basic?<><div className="resultTop"><small>EARLIEST FULL RETIREMENT</small><strong className="dateResult">{niceDate(basic.date)}</strong><span className="good">Maximum Allowance · No reduction</span></div><div className="stats"><div><span>Retirement age</span><b>{ageYM(basic.age)}</b></div><div><span>Time from today</span><b>{untilYM(today,basic.date)}</b></div><div><span>Creditable service</span><b>{ym(basic.service)}</b></div><div><span>Why you qualify</span><b>{basic.reason}</b></div></div><div className="basicPension"><span>ESTIMATED MAXIMUM ALLOWANCE</span><strong>{money(basic.monthly)}<i>/mo</i></strong><small>{money(basic.annual)} per year · using the AFC entered above</small></div><NetEstimate monthly={basic.monthly} settings={tax} dob={dob} date={basic.date} type={type}/><p className="basicNote">Basic mode assumes your AFC stays at the amount entered and does not include future sick leave, vacation conversion or other service credit.</p></>:<div className="emptyResult"><span>YOUR RESULT</span><b>Enter your information</b><p>Your earliest unreduced LGERS retirement date and Maximum Allowance will appear here.</p></div>}</aside></div>:<div className="calc advancedCalc"><div className="formPanel"><div className="sectionLabel">01 / YOUR LGERS RECORD</div><h2>Tell us where you are today.</h2>
 <Field label="I am a"><select value={type} onChange={e=>setType(e.target.value)}><option value="fire">Firefighter / Rescue Worker</option><option value="leo">Law Enforcement Officer</option><option value="general">Other Local Government Employee</option></select></Field>
 <div className="grid2"><Field label="Date of birth"><input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></Field><Field label="Current AFC" prefix="$" hint="Highest 48 consecutive months" info="Average Final Compensation (AFC) is generally your highest 48 consecutive months of eligible LGERS compensation. Use the AFC shown in ORBIT if you have it."><input value={commas(afc)} onChange={e=>setAfc(raw(e))}/></Field></div>
 <div className="grid2"><Field label="LGERS service — years" info="Your creditable LGERS service already earned, in full years. This can include eligible membership and purchased service shown by ORBIT."><input type="number" min="0" value={sy} onChange={e=>setSy(e.target.value)}/></Field><Field label="Additional months" info="Enter the months of creditable service beyond your full years. Example: 18 years 7 months = 18 years here and 7 additional months."><input type="number" min="0" max="11" value={sm} onChange={e=>setSm(e.target.value)}/></Field></div>
 {type==="leo"&&<Field label="Years served as a sworn LEO"><input type="number" min="0" value={leoY} onChange={e=>setLeoY(e.target.value)}/></Field>}
 <div className="sectionLabel gap">02 / YOUR FUTURE</div><div className="grid2"><Field label="Current annual salary" prefix="$" hint="Future AFC blends salary into a 48-month estimate"><input value={commas(salary)} onChange={e=>setSalary(raw(e))}/></Field><Field label="Expected annual raise" suffix="%"><div className="suffix"><input type="number" step=".1" value={raise} onChange={e=>setRaise(e.target.value)}/></div></Field></div>
 <div className="grid2"><Field label="Current unused sick leave (hours)" suffix="hrs" hint={"≈ "+c.currentSick.days.toFixed(1)+" LGERS sick-leave days"} info="Enter the unused eligible sick leave currently on your employer record. For this planning estimate, hours are converted using the monthly accrual rate you enter below."><input type="number" min="0" value={sick} onChange={e=>setSick(e.target.value)}/></Field><Field label="Sick leave earned each month (hours)" suffix="hrs/mo" hint="Use your employer's current accrual policy" info="This is important for LGERS. Retirement Systems instructs employers to convert sick-leave hours to days using the hours per month the leave was awarded when earned."><input type="number" min="0.1" step=".1" value={sickMonthly} onChange={e=>setSickMonthly(e.target.value)}/></Field></div>
 <label className="sickToggle"><input type="checkbox" checked={projectSick} onChange={e=>setProjectSick(e.target.checked)}/><span><b>Estimate the sick leave I will accumulate between now and retirement</b><small>{projectSick?"Yes — future accrual and expected usage will be included.":"No — only my current unused sick leave will be used."}</small></span><Info text="When enabled, the calculator projects your future sick balance for every potential retirement month. That projected balance can move your estimated 30-year Maximum Allowance date earlier."/></label>
 {projectSick&&<div className="projectionBox"><div className="grid2"><Field label="Sick leave you expect to use" suffix="%" hint="Percent of newly accrued sick leave"><div className="suffix"><input type="number" min="0" max="100" value={sickUsePct} onChange={e=>setSickUsePct(e.target.value)}/><i>%</i></div></Field><Field label="Does unused vacation convert to sick leave?" info="Vacation-to-sick conversion is an employer policy, not a universal LGERS rule. Only enter leave your employer actually converts to eligible sick leave."><select value={vacToSick?"yes":"no"} onChange={e=>setVacToSick(e.target.value==="yes")}><option value="no">No</option><option value="yes">Yes</option></select></Field></div>
 {vacToSick&&<><div className="grid2"><Field label="Vacation hours earned each year" suffix="hrs/yr" hint="Your annual vacation accrual"><input type="number" min="0" value={vacEarnAnnual} onChange={e=>setVacEarnAnnual(e.target.value)}/></Field><Field label="Vacation you expect to use" suffix="%"><div className="suffix"><input type="number" min="0" max="100" value={vacUsePct} onChange={e=>setVacUsePct(e.target.value)}/><i>%</i></div></Field></div><Field label="Unused vacation converted to sick leave" suffix="%" hint="Kure Beach policy: 100%"><div className="suffix"><input type="number" min="0" max="100" value={vacConvertPct} onChange={e=>setVacConvertPct(e.target.value)}/><i>%</i></div></Field></>}
 <div className="projectionSummary"><span>Projected eligible leave {leaveProjection.date?"by "+niceDate(leaveProjection.date):""}</span><b>{Math.round(leaveProjection.hours).toLocaleString()} hours</b><small>{retire?"Using your selected retirement date":"Using your calculated earliest Maximum Allowance date"} · current sick + future retained sick + eligible unused vacation converted to sick</small><div className="projectionBreakdown"><span><b>{Math.round(Number(sick||0)).toLocaleString()}</b>current sick hrs</span><span><b>{Math.round(leaveProjection.futureSick).toLocaleString()}</b>future sick hrs</span><span><b>{Math.round(leaveProjection.futureVac).toLocaleString()}</b>vacation → sick hrs</span></div><small>≈ {leaveProjection.days.toFixed(1)} LGERS sick-leave days → {leaveProjection.months} months estimated service credit</small></div></div>}
 <label className="sickToggle"><input type="checkbox" checked={useSick} onChange={e=>setUseSick(e.target.checked)}/><span><b>Use eligible sick leave toward retirement service credit</b><small>{useSick?"Yes — projected sick leave will be added when testing retirement eligibility.":"No — sick leave will not be added to service or eligibility calculations."}</small></span><Info text="Eligible unused sick leave can increase creditable service at retirement and can help complete service milestones such as 30 years. It generally requires your last day with the participating LGERS employer to be within 365 days before retirement."/></label><div className="grid2"><Field label="Beneficiary date of birth" hint="Used for survivor-option estimates"><input type="date" value={beneficiaryDob} onChange={e=>setBeneficiaryDob(e.target.value)}/></Field><Field label="Retirement date"><input type="date" min={today} value={retire} onChange={e=>setRetire(e.target.value)}/></Field></div></div>
 <aside className="results"><div className="resultTop"><small>{retire?"PROJECTED MONTHLY PENSION":"RETIREMENT TODAY"}</small><strong>{money(c.monthly)}<i>/mo</i></strong><span className={c.r===1?"good":c.r>0?"warn":"muted"}>{label(c.r)}</span></div>
 <div className="stats"><div><span>Annual pension</span><b>{money(c.annual)}</b></div><div><span>Retirement age</span><b>{ageYM(c.age)}</b></div><div><span>Total creditable service</span><b>{ym(c.service)}</b></div><div><span>Service entered today</span><b>{ym(c.cs)}</b></div><div><span>Additional service from working</span><b>{ym(c.future)}</b></div><div><span>{c.future>0?"Estimated future AFC":"Current AFC"}</span><b>{money(c.pa)}</b></div>{c.r>0&&c.r<1&&<div><span>Benefit factor</span><b>{Math.round(c.r*100)}%</b></div>}{useSick&&c.sickMonths>0&&<div><span>Sick leave credit</span><b>{ym(c.sickMonths/12)}</b></div>}</div>
 <NetEstimate monthly={c.monthly} settings={tax} dob={dob} date={retire||today} type={type}/>
 <div className="earned leaveNow"><span>IF YOU LEFT LGERS EMPLOYMENT TODAY <Info text="Current AFC and employment service are frozen. Selected current sick leave is included when the pension can start within 365 days of separation. Future salary, service and leave accrual are excluded."/></span><strong>{leaveNow.todayFactor>0?money(leaveNow.todayAmount):"Not eligible today"}{leaveNow.todayFactor>0&&<i>/mo</i>}</strong>{leaveNow.todayFactor>0&&<NetEstimate monthly={leaveNow.todayAmount} settings={tax} dob={dob} date={today} type={type} compact/>}<p className="earnedIntro">{leaveNow.todayFactor>0?"Benefit available using today's AFC and "+ym(leaveNow.todayService)+" of total creditable service.":"Your earned benefit can begin on the dates below. No further employment service or salary growth is assumed."}</p><div className="leaveChoices"><div><small>EARLIEST YOU COULD START A PENSION</small>{leaveNow.first?<><b>{niceDate(leaveNow.first.date)} · Age {ageYM(leaveNow.first.age)}</b><strong>{money(leaveNow.first.amount)}/mo</strong><em>{leaveNow.first.factor===1?"Maximum Allowance — no reduction":"Reduced early-retirement benefit"}</em><em>{ym(leaveNow.first.service)} total service · {ym(leaveNow.first.sickCredit)} sick credit</em><NetEstimate monthly={leaveNow.first.amount} settings={tax} dob={dob} date={leaveNow.first.date} type={type} compact/></>:<b>No eligible benefit with current service</b>}</div><div><small>EARLIEST WITHOUT ANY REDUCTION</small>{leaveNow.max?<><b>{niceDate(leaveNow.max.date)} · Age {ageYM(leaveNow.max.age)}</b><strong>{money(leaveNow.max.amount)}/mo</strong><em>Today's AFC · {ym(leaveNow.max.service)} total service</em><em>{ym(leaveNow.max.sickCredit)} sick credit included</em><NetEstimate monthly={leaveNow.max.amount} settings={tax} dob={dob} date={leaveNow.max.date} type={type} compact/></>:<b>No eligible benefit with current service</b>}</div></div></div><div className="options"><div className="optionHead"><span>PAYMENT OPTIONS AT RETIREMENT</span><small>Your Maximum Allowance is calculated here. NC calculates Options 2, 3, 6-2 and 6-3 as actuarial equivalents using individual factors including both ages and the payment start date.</small></div>
<div className="optionRow featured"><div><b>Maximum Allowance <Info text="Your highest monthly lifetime LGERS payment. Payments stop at your death; no continuing monthly survivor benefit."/></b><small>You receive the full calculated amount for life · Survivor receives $0 monthly after your death</small></div><strong>{money(c.monthly)}/mo</strong></div><NetEstimate monthly={c.monthly} settings={tax} dob={dob} date={retire||today} type={type} compact/>
<div className="optionRow optionDetailed"><div><b>Option 2 · 100% Joint & Survivor <Info text="You receive an actuarially reduced lifetime payment. After your death, the same monthly amount continues to your designated survivor for life. If the beneficiary is not your spouse, federal limits can affect the permitted amount."/></b><small>YOU: reduced lifetime payment</small><small>SURVIVOR: 100% of your Option 2 payment for life</small></div><strong>Personalized factor<br/>from ORBIT</strong></div>
<div className="optionRow optionDetailed"><div><b>Option 3 · 50% Joint & Survivor <Info text="You receive an actuarially reduced lifetime payment. After your death, one-half of that monthly amount continues to your designated survivor for life."/></b><small>YOU: reduced lifetime payment</small><small>SURVIVOR: 50% of your Option 3 payment for life</small></div><strong>Personalized factor<br/>from ORBIT</strong></div>
<div className="optionRow optionDetailed"><div><b>Option 6-2 · Modified 100% <Info text="Like Option 2, your survivor receives 100% of your reduced payment after your death. If your beneficiary dies before you, your own payment increases to the Maximum Allowance going forward."/></b><small>YOU: reduced lifetime payment</small><small>SURVIVOR: 100% · If beneficiary dies first, you pop up to {money(c.monthly)}/mo</small></div><strong>Personalized factor<br/>from ORBIT</strong></div>
<div className="optionRow optionDetailed"><div><b>Option 6-3 · Modified 50% <Info text="Like Option 3, your survivor receives 50% of your reduced payment after your death. If your beneficiary dies before you, your own payment increases to the Maximum Allowance going forward."/></b><small>YOU: reduced lifetime payment</small><small>SURVIVOR: 50% · If beneficiary dies first, you pop up to {money(c.monthly)}/mo</small></div><strong>Personalized factor<br/>from ORBIT</strong></div>
<div className="officialExample"><span>OFFICIAL NC EXAMPLE · MEMBER AGE 57 · BENEFICIARY AGE 51 · $2,000 MAXIMUM</span><div><b>Option 2</b><strong>$1,834.60</strong><small>survivor $1,834.60</small></div><div><b>Option 3</b><strong>$1,913.80</strong><small>survivor $956.90</small></div><div><b>Option 6-2</b><strong>$1,822.60</strong><small>survivor $1,822.60</small></div><div><b>Option 6-3</b><strong>$1,907.20</strong><small>survivor $953.60</small></div><p>Example only. NC states actual option amounts are calculated individually based on factors such as member age, beneficiary age and when payments begin.</p></div>
</div></aside></div>}</section>
 <section className="earliest"><div><div className="sectionLabel">03 / EARLIEST MAXIMUM ALLOWANCE</div><h2>What is the earliest I can retire with no reduction?</h2><p>This finds the first projected month you satisfy an unreduced LGERS retirement path using the information above{useSick?" and your selected sick-leave service credit":""}.</p></div>{earliestMax&&<div className="earliestCard"><small>EARLIEST PROJECTED UNREDUCED RETIREMENT</small><strong>{niceDate(earliestMax.date)}</strong><div className="earliestStats"><span><b>Age {ageYM(earliestMax.age)}</b>Age at earliest retirement</span><span><b>{ym(earliestMax.service)}</b>Total creditable service</span><span><b>{ym(c.cs)}</b>Service entered today</span><span><b>{untilYM(today,earliestMax.date)}</b>Additional service from working</span><span><b>{money(earliestMax.projectedAfc)}</b>Projected AFC</span><span><b>{money(earliestMax.monthly)}/mo</b>Maximum Allowance</span>{useSick&&<span><b>{Math.round(earliestMax.sickHours).toLocaleString()} hrs</b>Projected sick leave</span>}{useSick&&<span><b>{ym(earliestMax.sickMonths/12)}</b>Sick-leave service credit</span>}</div><NetEstimate monthly={earliestMax.monthly} settings={tax} dob={dob} date={earliestMax.date} type={type}/><em>{earliestMax.reason}</em><div className="dateDetail"><b>{untilYM(today,earliestMax.date)}</b><span>from today · {niceDate(earliestMax.date)}</span></div>{useSick&&<div className="leaveImpact"><small>YOUR PROJECTED LEAVE BENEFIT</small><div className="leaveImpactGrid"><div><span>Leave credit at retirement</span><b>{ym(earliestMax.sickMonths/12)}</b></div><div><span>Retirement accelerated by</span><b>{leaveAdvantage>0?ym(leaveAdvantage/12):"0 months"}</b></div><div><span>Pension added by leave credit</span><b>+{money(earliestMax.pensionAdded)}/mo</b></div></div><p>That monthly increase comes from counting eligible leave as creditable service in the 1.85% × AFC × service formula.</p></div>}</div>}</section><section id="timeline" className="timeline"><div className="sectionLabel">04 / LOOK AHEAD</div><h2>What happens if you stay?</h2><p className="lead">Same assumptions. Different dates. See the tradeoff.</p><div className="cards">{miles.map(x=><div className="mile" key={x.n}><small>{x.n===0?"TODAY":"+"+x.n+" YEARS"}</small><b>{x.r?money(x.m):"Not eligible"}</b><span>{ym(x.s)} service</span><span>Age {ageYM(x.a)}</span><span>{x.n===0?"Today":untilYM(today,addYears(today,x.n))+" from today"}</span><em>{x.r===1?"UNREDUCED":x.r>0?"REDUCED":"DEFERRED"}</em><NetEstimate monthly={x.m} settings={tax} dob={dob} date={addYears(today,x.n)} type={type} compact/></div>)}</div></section>
 <section id="how" className="how"><div><div className="sectionLabel">HOW IT WORKS</div><h2>Built around the LGERS formula—not your account balance.</h2></div><div className="howGrid"><article><b>1.85%</b><span>Benefit multiplier</span></article><article><b>AFC</b><span>Highest 48 consecutive months</span></article><article><b>Service</b><span>Creditable LGERS service</span></article></div></section>
 <section className="notice"><b>Planning estimate, not an official benefit calculation.</b><p>NC Retirement Compass is an independent educational tool and is not affiliated with the North Carolina Retirement Systems. Actual benefits are determined by the Retirement Systems Division under applicable law. Confirm retirement decisions with your official ORBIT estimate.</p><div><a href="https://www.myncretirement.com/" target="_blank" rel="noreferrer">NC Retirement Systems ↗</a><a href="https://orbit.myncretirement.com/" target="_blank" rel="noreferrer">ORBIT ↗</a></div></section>
 <footer><b>NC RETIREMENT COMPASS</b><span>Clearer retirement planning for North Carolina public servants.</span></footer></main>
}

